# Generated by Django 2.2.12 on 2021-03-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_nav',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.User', verbose_name='uid')),
                ('urls', models.CharField(max_length=128, verbose_name='网址收藏')),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.BooleanField(blank=True, default=1, verbose_name='性别')),
                ('wallet', models.IntegerField(default=0, verbose_name='G币')),
                ('headpic', models.ImageField(blank=True, null=True, upload_to='headpic', verbose_name='照片')),
                ('whatup', models.CharField(max_length=32, verbose_name='个性签名')),
                ('uaddress', models.CharField(max_length=64, verbose_name='地址')),
                ('lastonline_time', models.DateTimeField(verbose_name='最后上线时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='uid')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False, verbose_name='信息编号')),
                ('message', models.CharField(max_length=128, verbose_name='消息内容')),
                ('message_status', models.CharField(max_length=2, verbose_name='消息状态')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.User', verbose_name='收信人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.User', verbose_name='发信人')),
            ],
        ),
    ]
