# Generated by Django 2.2.12 on 2021-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='lastonline_time',
            field=models.DateTimeField(null=True, verbose_name='最后上线时间'),
        ),
    ]
