# Generated by Django 2.2.12 on 2021-03-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False, verbose_name='任务id')),
                ('price', models.IntegerField(default=0, verbose_name='任务赏金')),
                ('task_status', models.CharField(default='00', max_length=2)),
                ('reated_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('accer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accer', to='user.User', verbose_name='接受人')),
                ('inier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inier', to='user.User', verbose_name='发布人')),
            ],
        ),
    ]
