# Generated by Django 2.2.12 on 2021-03-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210302_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_contents',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='task.Task')),
                ('task_title', models.CharField(max_length=64, verbose_name='任务主题')),
                ('text', models.TextField(verbose_name='文字内容')),
                ('pic', models.ImageField(null=True, upload_to='task_pic', verbose_name='图片内容')),
            ],
        ),
    ]
