# Generated by Django 2.2.12 on 2021-03-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_contents',
            name='text',
            field=models.TextField(max_length=1280, verbose_name='文字内容'),
        ),
    ]
